{% set name = "hpp-doc" %}
{% set version = "4.15.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/humanoid-path-planner/hpp-doc/releases/download/v{{ version }}/hpp-doc-4.10.0.tar.gz
  sha256: 746137af0e705cdbe71029f48d594a8aaa0d8d3b577ea1599e62417a99c0f263

build:
  number: 2
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage(name|lower, max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make
    - pkg-config
    - doxygen
    - {{ cdt('mesa-libgl-devel') }}       # [linux]
    - {{ cdt('mesa-dri-drivers') }}       # [linux]
    - {{ cdt('libselinux-devel') }}       # [linux]
  host:
    - libboost-devel
    - qt-main
    - hpp-practicals
    - hpp-tutorial
  run:

test:
  requires:
    - pkg-config
  commands:
    - pkg-config --modversion {{ name }}

about:
  home: https://github.com/humanoid-path-planner/{{ name }}
  license: LGPL-3.0-or-later
  license_file: COPYING
  summary: {{ name }} subpackage of Humanoid Path Planner suite
  description: |
    HPP (Humanoid Path Planner) is a collection of software packages implementing
    path planning functionalities for a humanoid robot. The core functionalities are well
    suited to solve classical path planning problems. It can be extended to path planning
    for other types of robots like digital actors for instance.
  doc_url: https://gepettoweb.laas.fr/hpp/hpp-doc/doxygen-html/index.html
  dev_url: https://github.com/humanoid-path-planner/{{ name }}

extra:
  recipe-maintainers:
    - ymontmarin
